"""
Export Engine -- generates PowerPoint, PDF, and Word from DataFrames.
"""
import os
import tempfile
from datetime import datetime
from pathlib import Path

import pandas as pd

# PowerPoint
from pptx import Presentation
from pptx.util import Inches, Pt, Emu
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN

# PDF
from reportlab.lib.pagesizes import letter
from reportlab.lib.colors import HexColor
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

# Word
from docx import Document
from docx.shared import Pt as DocxPt, Inches as DocxInches, RGBColor as DocxRGB
from docx.enum.text import WD_ALIGN_PARAGRAPH


BG_DARK = "#0d1117"
BLUE = "#1f6feb"
GREEN = "#238636"
WHITE = "#ffffff"
GRAY = "#8b949e"


def _auto_summary(df):
    """One-paragraph summary from DataFrame stats."""
    rows, cols = df.shape
    num_cols = df.select_dtypes(include="number").columns.tolist()
    cat_cols = df.select_dtypes(include="object").columns.tolist()
    parts = [f"The dataset contains {rows:,} rows and {cols} columns."]
    if num_cols:
        parts.append(
            f"Numeric fields ({len(num_cols)}): "
            + ", ".join(num_cols[:5])
            + ("..." if len(num_cols) > 5 else "")
            + "."
        )
    if cat_cols:
        parts.append(
            f"Categorical fields ({len(cat_cols)}): "
            + ", ".join(cat_cols[:5])
            + ("..." if len(cat_cols) > 5 else "")
            + "."
        )
    if num_cols:
        top = num_cols[0]
        parts.append(
            f"{top} ranges from {df[top].min():,.2f} to {df[top].max():,.2f} "
            f"with a mean of {df[top].mean():,.2f}."
        )
    return " ".join(parts)


def _num_stats(df):
    """Return list of dicts with stats per numeric column."""
    out = []
    for col in df.select_dtypes(include="number").columns:
        out.append({
            "name": col,
            "min": df[col].min(),
            "max": df[col].max(),
            "mean": df[col].mean(),
            "median": df[col].median(),
            "nulls": int(df[col].isna().sum()),
        })
    return out


class ExportEngine:

    # ------------------------------------------------------------------ #
    #  PowerPoint                                                         #
    # ------------------------------------------------------------------ #
    def generate_pptx(self, df, title, output_path=None):
        if output_path is None:
            output_path = os.path.join(tempfile.gettempdir(), f"{title}.pptx")
        try:
            print(f"[ExportEngine] Generating PowerPoint: {title}")
            prs = Presentation()
            prs.slide_width = Inches(13.333)
            prs.slide_height = Inches(7.5)
            bg_rgb = RGBColor(0x0D, 0x11, 0x17)
            blue_rgb = RGBColor(0x1F, 0x6F, 0xEB)
            white_rgb = RGBColor(0xFF, 0xFF, 0xFF)
            gray_rgb = RGBColor(0x8B, 0x94, 0x9E)

            def _set_bg(slide):
                bg = slide.background
                fill = bg.fill
                fill.solid()
                fill.fore_color.rgb = bg_rgb

            def _add_text(slide, left, top, width, height, text,
                          size=18, color=white_rgb, bold=False, align=PP_ALIGN.LEFT):
                txBox = slide.shapes.add_textbox(
                    Inches(left), Inches(top), Inches(width), Inches(height)
                )
                tf = txBox.text_frame
                tf.word_wrap = True
                p = tf.paragraphs[0]
                p.text = str(text)
                p.font.size = Pt(size)
                p.font.color.rgb = color
                p.font.bold = bold
                p.alignment = align

            # -- Title slide --
            sl = prs.slides.add_slide(prs.slide_layouts[6])  # blank
            _set_bg(sl)
            _add_text(sl, 1, 2.2, 11, 1.5, title, size=36, color=blue_rgb, bold=True,
                      align=PP_ALIGN.CENTER)
            _add_text(sl, 1, 4, 11, 0.6, datetime.now().strftime("%B %d, %Y"),
                      size=16, color=gray_rgb, align=PP_ALIGN.CENTER)
            _add_text(sl, 1, 4.8, 11, 0.6, "Generated by Dr. Data",
                      size=14, color=gray_rgb, align=PP_ALIGN.CENTER)

            # -- Overview slide --
            rows, cols = df.shape
            stats = _num_stats(df)
            sl = prs.slides.add_slide(prs.slide_layouts[6])
            _set_bg(sl)
            _add_text(sl, 0.8, 0.4, 6, 0.6, "Data Overview", size=28, color=blue_rgb, bold=True)
            overview = (
                f"Rows: {rows:,}    Columns: {cols}\n"
                f"Numeric columns: {len(stats)}    "
                f"Categorical columns: {len(df.select_dtypes(include='object').columns)}\n"
                f"Null cells: {int(df.isna().sum().sum()):,}"
            )
            _add_text(sl, 0.8, 1.4, 11, 3, overview, size=18)

            # -- Per-numeric-column slides --
            for s in stats[:10]:
                sl = prs.slides.add_slide(prs.slide_layouts[6])
                _set_bg(sl)
                _add_text(sl, 0.8, 0.4, 10, 0.6, s["name"], size=28, color=blue_rgb, bold=True)
                body = (
                    f"Min: {s['min']:,.2f}\n"
                    f"Max: {s['max']:,.2f}\n"
                    f"Mean: {s['mean']:,.2f}\n"
                    f"Median: {s['median']:,.2f}\n"
                    f"Null values: {s['nulls']:,}"
                )
                _add_text(sl, 0.8, 1.4, 11, 4, body, size=20)

            # -- Takeaways slide --
            sl = prs.slides.add_slide(prs.slide_layouts[6])
            _set_bg(sl)
            _add_text(sl, 0.8, 0.4, 10, 0.6, "Key Takeaways", size=28, color=blue_rgb, bold=True)
            _add_text(sl, 0.8, 1.4, 11, 4.5, _auto_summary(df), size=18)

            prs.save(output_path)
            print(f"[ExportEngine] PowerPoint saved: {output_path}")
            return output_path
        except Exception as e:
            print(f"[ExportEngine] PowerPoint failed: {e}")
            return None

    # ------------------------------------------------------------------ #
    #  PDF                                                                #
    # ------------------------------------------------------------------ #
    def generate_pdf(self, df, title, output_path=None):
        if output_path is None:
            output_path = os.path.join(tempfile.gettempdir(), f"{title}.pdf")
        try:
            print(f"[ExportEngine] Generating PDF: {title}")
            doc = SimpleDocTemplate(
                output_path, pagesize=letter,
                topMargin=0.5 * inch, bottomMargin=0.5 * inch,
                leftMargin=0.5 * inch, rightMargin=0.5 * inch,
            )
            styles = getSampleStyleSheet()
            title_style = ParagraphStyle(
                "DrTitle", parent=styles["Title"],
                fontSize=22, textColor=HexColor(BLUE), spaceAfter=12,
            )
            body_style = ParagraphStyle(
                "DrBody", parent=styles["Normal"],
                fontSize=10, textColor=HexColor("#c9d1d9"), spaceAfter=8,
                leading=14,
            )
            heading_style = ParagraphStyle(
                "DrHeading", parent=styles["Heading2"],
                fontSize=14, textColor=HexColor(BLUE), spaceAfter=6,
            )

            elements = []
            elements.append(Paragraph(title, title_style))
            elements.append(Paragraph(
                datetime.now().strftime("%B %d, %Y"), body_style
            ))
            elements.append(Spacer(1, 12))

            # Executive summary
            elements.append(Paragraph("Executive Summary", heading_style))
            elements.append(Paragraph(_auto_summary(df), body_style))
            elements.append(Spacer(1, 12))

            # Stats table
            stats = _num_stats(df)
            if stats:
                elements.append(Paragraph("Statistical Summary", heading_style))
                header = ["Column", "Min", "Max", "Mean", "Median", "Nulls"]
                data = [header]
                for s in stats[:15]:
                    data.append([
                        s["name"][:20],
                        f"{s['min']:,.2f}", f"{s['max']:,.2f}",
                        f"{s['mean']:,.2f}", f"{s['median']:,.2f}",
                        str(s["nulls"]),
                    ])
                t = Table(data, repeatRows=1)
                t.setStyle(TableStyle([
                    ("BACKGROUND", (0, 0), (-1, 0), HexColor(BLUE)),
                    ("TEXTCOLOR", (0, 0), (-1, 0), HexColor(WHITE)),
                    ("FONTSIZE", (0, 0), (-1, -1), 8),
                    ("GRID", (0, 0), (-1, -1), 0.5, HexColor(GRAY)),
                    ("ROWBACKGROUNDS", (0, 1), (-1, -1),
                     [HexColor("#161b22"), HexColor("#1c2128")]),
                    ("TEXTCOLOR", (0, 1), (-1, -1), HexColor("#c9d1d9")),
                    ("ALIGN", (1, 0), (-1, -1), "RIGHT"),
                ]))
                elements.append(t)
                elements.append(Spacer(1, 12))

            # Data preview
            elements.append(Paragraph("Data Preview (first 20 rows)", heading_style))
            preview = df.head(20)
            cols = preview.columns.tolist()
            show_cols = cols[:8]  # limit width
            header_row = [str(c)[:18] for c in show_cols]
            tbl_data = [header_row]
            for _, row in preview.iterrows():
                tbl_data.append([str(row[c])[:18] for c in show_cols])
            t2 = Table(tbl_data, repeatRows=1)
            t2.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), HexColor(BLUE)),
                ("TEXTCOLOR", (0, 0), (-1, 0), HexColor(WHITE)),
                ("FONTSIZE", (0, 0), (-1, -1), 7),
                ("GRID", (0, 0), (-1, -1), 0.5, HexColor(GRAY)),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1),
                 [HexColor("#161b22"), HexColor("#1c2128")]),
                ("TEXTCOLOR", (0, 1), (-1, -1), HexColor("#c9d1d9")),
            ]))
            elements.append(t2)

            doc.build(elements)
            print(f"[ExportEngine] PDF saved: {output_path}")
            return output_path
        except Exception as e:
            print(f"[ExportEngine] PDF failed: {e}")
            return None

    # ------------------------------------------------------------------ #
    #  Word                                                               #
    # ------------------------------------------------------------------ #
    def generate_docx(self, df, title, output_path=None):
        if output_path is None:
            output_path = os.path.join(tempfile.gettempdir(), f"{title}.docx")
        try:
            print(f"[ExportEngine] Generating Word doc: {title}")
            doc = Document()

            # Style defaults
            style = doc.styles["Normal"]
            font = style.font
            font.name = "Calibri"
            font.size = DocxPt(11)
            font.color.rgb = DocxRGB(0xC9, 0xD1, 0xD9)

            # Title
            h = doc.add_heading(title, level=0)
            for run in h.runs:
                run.font.color.rgb = DocxRGB(0x1F, 0x6F, 0xEB)
            doc.add_paragraph(datetime.now().strftime("%B %d, %Y"))
            doc.add_paragraph("")

            # Executive summary
            h2 = doc.add_heading("Executive Summary", level=1)
            for run in h2.runs:
                run.font.color.rgb = DocxRGB(0x1F, 0x6F, 0xEB)
            doc.add_paragraph(_auto_summary(df))

            # Stats
            stats = _num_stats(df)
            if stats:
                h2 = doc.add_heading("Statistical Analysis", level=1)
                for run in h2.runs:
                    run.font.color.rgb = DocxRGB(0x1F, 0x6F, 0xEB)
                table = doc.add_table(rows=1, cols=6)
                table.style = "Table Grid"
                hdr = table.rows[0].cells
                for i, label in enumerate(
                    ["Column", "Min", "Max", "Mean", "Median", "Nulls"]
                ):
                    hdr[i].text = label
                for s in stats[:15]:
                    row = table.add_row().cells
                    row[0].text = s["name"][:25]
                    row[1].text = f"{s['min']:,.2f}"
                    row[2].text = f"{s['max']:,.2f}"
                    row[3].text = f"{s['mean']:,.2f}"
                    row[4].text = f"{s['median']:,.2f}"
                    row[5].text = str(s["nulls"])
                doc.add_paragraph("")

            # Data table
            h2 = doc.add_heading("Data Preview", level=1)
            for run in h2.runs:
                run.font.color.rgb = DocxRGB(0x1F, 0x6F, 0xEB)
            preview = df.head(30)
            show_cols = preview.columns.tolist()[:8]
            table = doc.add_table(rows=1, cols=len(show_cols))
            table.style = "Table Grid"
            hdr = table.rows[0].cells
            for i, col in enumerate(show_cols):
                hdr[i].text = str(col)[:18]
            for _, data_row in preview.iterrows():
                row = table.add_row().cells
                for i, col in enumerate(show_cols):
                    row[i].text = str(data_row[col])[:20]

            doc.save(output_path)
            print(f"[ExportEngine] Word doc saved: {output_path}")
            return output_path
        except Exception as e:
            print(f"[ExportEngine] Word doc failed: {e}")
            return None

    # ------------------------------------------------------------------ #
    #  All formats                                                        #
    # ------------------------------------------------------------------ #
    def generate_all(self, df, title, output_dir=None):
        if output_dir is None:
            output_dir = tempfile.gettempdir()
        os.makedirs(output_dir, exist_ok=True)
        safe = "".join(c if c.isalnum() or c in " _-" else "_" for c in title)
        results = {}
        results["pptx"] = self.generate_pptx(
            df, title, os.path.join(output_dir, f"{safe}.pptx")
        )
        results["pdf"] = self.generate_pdf(
            df, title, os.path.join(output_dir, f"{safe}.pdf")
        )
        results["docx"] = self.generate_docx(
            df, title, os.path.join(output_dir, f"{safe}.docx")
        )
        return results
